// Code generated by goctl. DO NOT EDIT.
package types

type Task struct {
	Name          string         `json:"name"`          //压测任务名字
	Desc          string         `json:"desc"`          //压测描述
	TotalNum      int64          `json:"totalNum"`      //总人数
	Pace          int64          `json:"pace"`          //步调
	RunTime       int64          `json:"runTime"`       //执行时间（s）
	MachineConfig *StressMachine `json:"machineConfig"` //机器设置
	MaxRps        int64          `json:"maxRps"`        //最大rps【阈值】
}

type ExtraTask struct {
	OpNickName string `json:"opNickname"` //执行人
	DeleteTime string `json:"deleteTime"` //删除时间
	IsDeleted  int64  `json:"isDeleted"`  //0不删除，1已删除
	CreateTime string `json:"createTime"` //创建时间
	UpdateTime string `json:"updateTime"` //更新时间
	LastDoTime string `json:"lastDoTime"` //最后一次执行时间
	TaskFlag   int64  `json:"taskFlag"`   //类型1game2pressure
}

type StressMachine struct {
	Type            int64   `json:"type"`
	Number          int64   `json:"number"`
	MasterMachineId int64   `json:"masterMachineId"`
	MachineIds      []int64 `json:"machineIds"`
}

type TaskMonitor struct {
	MonitorConfig []GameMonitorConfig `json:"monitorConfig"`
}

type GameMonitorConfig struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	Url     string `json:"url"`
	Account string `json:"account"`
	Pwd     string `json:"pwd"`
	Type    int64  `json:"type"`
}

type Game struct {
	Url      string `json:"url"`      //git对应url
	Branch   string `json:"branch"`   //git对应分支
	EntryDir string `json:"entryDir"` //入口文件名称
	GitFlag  int64  `json:"gitFlag"`  //git类型 1、gitlab 2、gitee
}

type InsertTaskGameReq struct {
	Task
	Game
	TaskMonitor
}

type UpdateTaskGameReq struct {
	Id int64 `json:"id"`
	Task
	Game
	TaskMonitor
}

type DeleteTaskGameReq struct {
	Id int64 `path:"id"`
}

type GetGameTaskIdReq struct {
	Id int64 `path:"id"`
}

type GetGameTaskRsp struct {
	Id int64 `json:"id"`
	Task
	ExtraTask
	Game
	TaskMonitor
}

type GetGameTaskListReq struct {
	Name     string `json:"name,optional"`
	Page     int64  `json:"page,optional"`
	PageSize int64  `json:"pageSize,optional"`
}

type GetGameTaskListRsp struct {
	Total    int64             `json:"total"`
	Page     int64             `json:"page"`
	PageSize int64             `json:"pageSize"`
	List     []*GetGameTaskRsp `json:"list"`
}

type CommonRsp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}

type Machine struct {
	Name         string `json:"name"`
	OuternetIp   string `json:"outernetIp"`
	InnernetIp   string `json:"innernetIp"`
	CpuCores     int64  `json:"cpuCores"`
	Port         int64  `json:"port"`
	RamSize      int64  `json:"ramSize"`
	RootAccount  string `json:"rootAccount"`
	RootPassword string `json:"rootPassword"`
	NickName     string `json:"nickName"`
}

type InsertMachineReq struct {
	Machine
}

type UpdateMachineReq struct {
	Machine
	UserFlag int64 `json:"userFlag"`
}

type GetMachineIdReq struct {
	Id int64 `path:"id"`
}

type DeleteMachineReq struct {
	Id int64 `path:"id"`
}

type GetMachineRsp struct {
	Id int64 `json:"id"`
	Machine
	UserFlag    int64  `json:"userFlag"`
	WorkingFlag int64  `json:"workingFlag"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
	IsDelete    int64  `json:"isDelete"`
}

type GetMachineListReq struct {
	Name     string `json:"name,optional"`
	Page     int64  `json:"page,optional"`
	PageSize int64  `json:"pageSize,optional"`
}

type GetMachineListRsp struct {
	Total    int64            `json:"total"`
	Page     int64            `json:"page"`
	PageSize int64            `json:"pageSize"`
	List     []*GetMachineRsp `json:"list"`
}
