// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameFieldNames          = builder.RawFieldNames(&Game{})
	gameRows                = strings.Join(gameFieldNames, ",")
	gameRowsExpectAutoSet   = strings.Join(stringx.Remove(gameFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	gameRowsWithPlaceHolder = strings.Join(stringx.Remove(gameFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheHhxGameIdPrefix = "cache:hhx:game:id:"
)

type (
	gameModel interface {
		Insert(ctx context.Context, data *Game) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Game, error)
		Update(ctx context.Context, data *Game) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGameModel struct {
		sqlc.CachedConn
		table string
	}

	Game struct {
		Id       int64  `db:"id"`
		TaskId   int64  `db:"task_id"`   // task表对应id
		Url      string `db:"url"`       // git对应url
		Branch   string `db:"branch"`    // 分支名字
		EntryDir string `db:"entry_dir"` // 入口文件名字
		GitFlag  int64  `db:"git_flag"`  // 类型1gitlab2gitee
	}
)

func newGameModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultGameModel {
	return &defaultGameModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`game`",
	}
}

func (m *defaultGameModel) Delete(ctx context.Context, id int64) error {
	hhxGameIdKey := fmt.Sprintf("%s%v", cacheHhxGameIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, hhxGameIdKey)
	return err
}

func (m *defaultGameModel) FindOne(ctx context.Context, id int64) (*Game, error) {
	hhxGameIdKey := fmt.Sprintf("%s%v", cacheHhxGameIdPrefix, id)
	var resp Game
	err := m.QueryRowCtx(ctx, &resp, hhxGameIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameModel) Insert(ctx context.Context, data *Game) (sql.Result, error) {
	hhxGameIdKey := fmt.Sprintf("%s%v", cacheHhxGameIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, gameRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TaskId, data.Url, data.Branch, data.EntryDir, data.GitFlag)
	}, hhxGameIdKey)
	return ret, err
}

func (m *defaultGameModel) Update(ctx context.Context, data *Game) error {
	hhxGameIdKey := fmt.Sprintf("%s%v", cacheHhxGameIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TaskId, data.Url, data.Branch, data.EntryDir, data.GitFlag, data.Id)
	}, hhxGameIdKey)
	return err
}

func (m *defaultGameModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheHhxGameIdPrefix, primary)
}

func (m *defaultGameModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGameModel) tableName() string {
	return m.table
}
