// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	game "single/stressTask/internal/handler/game"
	machine "single/stressTask/internal/handler/machine"
	report "single/stressTask/internal/handler/report"
	"single/stressTask/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/game/add_task",
				Handler: game.InsertGameTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/game/update_task",
				Handler: game.UpdateGameTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/game/delete_task/:id",
				Handler: game.DeleteGameTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/game/get_task/:id",
				Handler: game.GetGameTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/game/get_task_list",
				Handler: game.GetGameTaskListHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/machine/add_machine",
				Handler: machine.InsertMachineHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/machine/update_machine",
				Handler: machine.UpdateMachineHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/machine/delete_machine/:id",
				Handler: machine.DeleteMachineHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/machine/get_machine/:id",
				Handler: machine.GetMachineHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/machine/get_machine_list",
				Handler: machine.GetMachineListHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/report/run_task",
				Handler: report.RunTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/report/get_report_list",
				Handler: report.GetReportListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/report/get_report/:id",
				Handler: report.GetReportHandler(serverCtx),
			},
		},
	)
}
